#!/usr/bin/env bash

# Creates Git configuration file with my settings and prints the current config.
#
# Latest revision: 2024-12-30
#
# Written and unlicensed by Mikołaj Bartnicki <mikolaj@bartnicki.org>;
# please read LICENSE file for details.

# Exit on first error
set -e

userName="Mikołaj Bartnicki"
userEmail="github@nikolaos.org"
coreEditor="vim"
coreExcludesFile="~/.gitignore"
pushAutoSetupRemote="true"

function Main() {
	git config --global user.name "$userName"
	git config --global user.email "$userEmail"
	git config --global core.editor "$coreEditor"
	git config --global core.excludesFile "$coreExcludesFile"
	git config --global push.autoSetupRemote "$pushAutoSetupRemote"
	git config --global --list
}

Main
